### ISSUE TITLE
UK flag is blank!!

### ISSUE THREAD

**Issue by roseKQ** [ivanoff/react-native-ico-flags#1]
This is a really good library which works really well but unfortunately the UK / Union jack flag icon is blank. Is there any way to fix this? Is there an alternative prop to get the flag? 

Thanks in advance

![Screenshot 2021-02-24 at 14 13 35](https://user-images.githubusercontent.com/11443407/109012982-87cfea00-76aa-11eb-8c9a-16e0965bf926.png)

**Comment by ivanoff** [comment]
I think, "united-kingdom" flag name is what you're looking for:

<Icon name="united-kingdom" />

http://ico.simpleness.org/icon/flags/united-kingdom

Thank you!

**Comment by roseKQ** [comment]
I am using this prop 

`<Icon name="united-kingdom" />`

which is the same as yours and it is still blank...

**Comment by ivanoff** [comment]
Could you check only this flag?

`$ cat App.js`

```
import React from 'react';
import Flag from 'react-native-ico-flags';

export default () => <Flag name="united-kingdom" />
```

**Comment by roseKQ** [comment]
Yes this fixed it! Thank you for the help
