### ISSUE TITLE
Req  - repository name

### ISSUE THREAD

**Issue by amerllica** [ivanoff/react-native-ico-flags#10]
This repository and its package name are the same `react-native-ico-flags`, is there a possibility to rename it to `react-native-nations-flags`, because there are a couple of nations and ethnics which they've got flags but still they are not known as countries?

Also, by having this repository name we can add some other props to select the country like `ISO-2` or `ISO-3` or some other features like adding possible area code for phone numbers

**Comment by ivanoff** [comment]
react-native-nations-flags@6.3.1

and phone codes too.

**Comment by amerllica** [comment]
I just checked and realized you created a new GitHub repository and a new NPMJS library. I think there is no need to do these. You could only rename both and do redirect the previous addresses. Keeping consistency is the first valuable criterion for having got a good product.

Now, never mind, I'll continue to send PRs on this repo, not the new one.
