### ISSUE TITLE
Could not find a declaration file for module 'react-native-ico-flags'. 

### ISSUE THREAD

**Issue by Ahmedhamed77** [ivanoff/react-native-ico-flags#3]
hello, thanks for this package but i'm trying to use the package with typescript but there is not types at all and it gives me error
is there any solution to that?

![Screenshot 2022-02-12 at 20 12 36](https://user-images.githubusercontent.com/39366327/153712838-71f80279-cea0-492a-8d72-b8007653ade7.png)

**Comment by rcfrias** [comment]
@Ahmedhamed77, apparently types are not included in this package, you will have to make TypeScript ignore this until TS support is added.
Any thoughts? @ivanoff ?

**Comment by ivanoff** [comment]
I've fixed it. Could you check please?
